package diet.server.experimentmanager;

import diet.server.ConversationController.ClassLoader.ClassLoad;
import diet.server.ConversationController.DefaultConversationController;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Vector;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sre
 */
public class JClassBrowser extends javax.swing.JPanel {

	JExperimentManagerMainFrame jemmf;
	JList publicJLIST1;

	public JClassBrowser(JExperimentManagerMainFrame jemmf) {
		initComponents();
		publicJLIST1 = jList1;
		this.jemmf = jemmf;

		ClassLoad cl = new ClassLoad();
		Vector v = ClassLoad.getConversationControllers();

		jList1.removeAll();
		jList1.setListData(v);
		this.repaint();
		jList1.repaint();
		jList1.addMouseListener(new JClassPopupMenu(this));

		SwingUtilities.updateComponentTreeUI(this);
		this.setVisible(true);
		this.jList1.setSelectedIndex(0);

	}

	/**
	 * Creates new form JClassBrowser
	 */
	public JClassBrowser() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPaneBOTTOM = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();

		setMinimumSize(new java.awt.Dimension(900, 500));
		setPreferredSize(new java.awt.Dimension(900, 500));
		setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

		jScrollPaneBOTTOM.setBackground(new java.awt.Color(255, 255, 255));
		jScrollPaneBOTTOM.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
		jScrollPaneBOTTOM.setOpaque(false);
		jScrollPaneBOTTOM.setPreferredSize(new java.awt.Dimension(350, 400));

		jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jList1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jList1MouseReleased(evt);
			}
		});
		jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
			public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				jList1ValueChanged(evt);
			}
		});
		jScrollPaneBOTTOM.setViewportView(jList1);

		add(jScrollPaneBOTTOM);

		jPanel1.setMaximumSize(new java.awt.Dimension(200, 4000));
		jPanel1.setPreferredSize(new java.awt.Dimension(180, 10));

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Demo on local machine:",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 1, 12))); // NOI18N

		jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jButton4.setText("Manual login");
		jButton4.setToolTipText(
				"<html>This starts the experimental script and also immediately starts clients on the local machine. <br>\nUse this for trying out / testing / debugging a script</html>");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jButton5.setText("Auto login");
		jButton5.setToolTipText(
				"<html>This option <br>\n(1) starts the experimental script <br>\n(2) starts the clients on the local machine <br>\n(3) attempts to log the clients in automatically - you don't need to enter the participant ID or the Username <br>\n<br>\nUse this option if you are sick of entering the participant ID while testing / debugging<br>\n</html>");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jButton6.setText("Additional Client");
		jButton6.setToolTipText(
				"<html>\nThis option starts an additional client on the local machine that attempts to login to the experimental script<br>\n</html>\n");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButton6,
								javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)));

		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Experiment:",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 1, 12))); // NOI18N
		jPanel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

		jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jButton1.setText("START");
		jButton1.setToolTipText("<html>Starts the experimental script<br>and waits for clients to connect</html>");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 374, Short.MAX_VALUE)
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

		add(jPanel1);
	}// </editor-fold>//GEN-END:initComponents

	private void jList1MouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jList1MouseReleased
		// TODO add your handling code here:
		if (evt.getButton() == MouseEvent.BUTTON2 || evt.getButton() == MouseEvent.BUTTON3) {

		}

	}// GEN-LAST:event_jList1MouseReleased

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
		// Auto-login
		String oSelected = (String) publicJLIST1.getSelectedValue();
		if (oSelected == null)
			return;
		DefaultConversationController.config.login_autologin = true;
		jemmf.expmanUI.runExperimentLocally(oSelected);

	}// GEN-LAST:event_jButton5ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		// TODO add your handling code here:
		// Manual login
		String oSelected = (String) publicJLIST1.getSelectedValue();
		if (oSelected == null)
			return;
		jemmf.expmanUI.runExperimentLocally(oSelected);
	}// GEN-LAST:event_jButton4ActionPerformed

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton6ActionPerformed
		String oSelected = (String) publicJLIST1.getSelectedValue();
		if (oSelected == null)
			return;
		DefaultConversationController.config.login_autologin = false;
		jemmf.expmanUI.createClientsLocally(1, this.jemmf.expmanUI.portNumber);
	}// GEN-LAST:event_jButton6ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// START
		String oSelected = (String) publicJLIST1.getSelectedValue();
		if (oSelected == null)
			return;
		jemmf.expmanUI.runExperiment(oSelected);
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_jList1ValueChanged
		// TODO add your handling code here:
		String oSelected = (String) publicJLIST1.getSelectedValue();
		if (oSelected == null) {
			jButton1.setEnabled(false);
			jButton4.setEnabled(false);
			jButton5.setEnabled(false);
			jButton6.setEnabled(false);
		} else {
			jButton1.setEnabled(true);
			jButton4.setEnabled(true);
			jButton5.setEnabled(true);
			jButton6.setEnabled(true);
		}

	}// GEN-LAST:event_jList1ValueChanged

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JList jList1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPaneBOTTOM;
	// End of variables declaration//GEN-END:variables

	public class JClassPopupMenu extends JPopupMenu implements MouseListener, ActionListener {

		JClassBrowser jcb;

		public JClassPopupMenu(JClassBrowser jcb) {
			this.jcb = jcb;
		}

		public void actionPerformed(ActionEvent e) {
			// System.out.println(e.getSource().getClass().toString());
			System.out.println(((JMenuItem) e.getSource()).getText());
			String choice = (((JMenuItem) e.getSource()).getText());
			if (choice.equalsIgnoreCase("Run as new experiment")) {
				String oSelected = (String) publicJLIST1.getSelectedValue();
				if (oSelected == null)
					return;
				jcb.jemmf.expmanUI.runExperiment(oSelected);
			} else if (choice.equalsIgnoreCase("Run locally as demo")) {
				String oSelected = (String) publicJLIST1.getSelectedValue();
				if (oSelected == null)
					return;
				jcb.jemmf.expmanUI.runExperimentLocally(oSelected);
			}

			// jemmf.expmanUI.expmanager.createAndActivateNewExperiment(((JMenuItem)e.getSource()).getText());
		}

		public void mouseClicked(MouseEvent e) {
		}

		public void mouseEntered(MouseEvent e) {
		}

		public void mouseExited(MouseEvent e) {
		}

		public void mousePressed(MouseEvent e) {
			if (e.isPopupTrigger()) {
				maybeShowPopup(e);
			}
		}

		public void mouseReleased(MouseEvent e) {
			if (e.isPopupTrigger()) {
				maybeShowPopup(e);
			}

		}

		public void maybeShowPopup(MouseEvent e) {
			// System.exit(-3);
			Object o = e.getSource();
			if (o instanceof JList) {
				JList jl = (JList) o;
				Object oSelected = (String) jl.getSelectedValue();
				if (oSelected == null)
					return;

				JPopupMenu popup = new JPopupMenu();
				JMenuItem menuItem = new JMenuItem("Run as new experiment");

				menuItem.addActionListener(this);
				popup.add(menuItem);
				menuItem = new JMenuItem("Run locally as demo");
				menuItem.addActionListener(this);
				popup.add(menuItem);
				if (e.isPopupTrigger()) {
					popup.show(e.getComponent(), e.getX(), e.getY());
				}

			}
		}

	}

}
