/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package diet.textmanipulationmodules.WhitelistBlacklistFilterTrigger;

/**
 *
 * @author gj
 */
public class JSimpleWhitelistOfDutchOK extends javax.swing.JFrame {

	WhitelistBlacklistFilterTrigger wbft;

	public JSimpleWhitelistOfDutchOK(WhitelistBlacklistFilterTrigger wbf) {
		this.wbft = wbf;
		initComponents();
		this.setVisible(true);
	}

	/**
	 * Creates new form JSimpleWhitelistOfDutchOK
	 */
	public JSimpleWhitelistOfDutchOK() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTextField1WHITELISTOFTURNS = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jTextField2WHITELISTOFWORDS = new javax.swing.JTextField();
		jTextField3BLACKLISTOFTURNS = new javax.swing.JTextField();
		jTextField4BLACKLISTOFWORDS = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jTextField5BLACKLISTENDOFTURN = new javax.swing.JTextField();
		jButton5 = new javax.swing.JButton();
		jTextField6BLACKLISTPUNCTUATION = new javax.swing.JTextField();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jTextField1WHITELISTOFTURNS.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1WHITELISTOFTURNSActionPerformed(evt);
			}
		});

		jButton1.setText("Add to Whitelist of Turns");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jTextField3BLACKLISTOFTURNS.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField3BLACKLISTOFTURNSActionPerformed(evt);
			}
		});

		jButton2.setText("Add to Whitelist of Words");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("Add to Blacklist of Turns");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setText("Add to Blacklist of Words");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jLabel1.setText("Please make a written note of any changes!");

		jButton5.setText("Add to Blacklist of END OF TURN");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton6.setText("Add to Blacklist of PUNCTUATION");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jButton7.setText("PANIC BUTTON TO RESET TO DEFAULTS (ONLY USE IN EMERGENCY!)");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup().addGap(30, 30, 30)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jTextField6BLACKLISTPUNCTUATION)
														.addComponent(jTextField5BLACKLISTENDOFTURN)
														.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
																244, Short.MAX_VALUE)
										.addComponent(jTextField4BLACKLISTOFWORDS)
										.addComponent(jTextField3BLACKLISTOFTURNS)
										.addComponent(jTextField2WHITELISTOFWORDS)
										.addComponent(jTextField1WHITELISTOFTURNS))
										.addGap(41, 41, 41)
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 204,
														Short.MAX_VALUE))
												.addGap(0, 0, Short.MAX_VALUE)))
										.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(30, 30, 30)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField1WHITELISTOFTURNS, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton1))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jTextField2WHITELISTOFWORDS, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton2))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jTextField3BLACKLISTOFTURNS, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton3))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jTextField4BLACKLISTOFWORDS, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton4))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jTextField5BLACKLISTENDOFTURN, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton5))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jTextField6BLACKLISTPUNCTUATION, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton6)).addGap(18, 18, 18).addComponent(jLabel1).addGap(18, 18, 18)
				.addComponent(jButton7).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextField1WHITELISTOFTURNSActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1WHITELISTOFTURNSActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField1WHITELISTOFTURNSActionPerformed

	private void jTextField3BLACKLISTOFTURNSActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField3BLACKLISTOFTURNSActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField3BLACKLISTOFTURNSActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		// BLACKLIST OF WORDS // TODO add your handling code here:
		this.wbft.addToBlacklistWord(this.jTextField4BLACKLISTOFWORDS.getText());
	}// GEN-LAST:event_jButton4ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// WHITELIST OF TURNS
		this.wbft.addToWhitelistTurn(this.jTextField1WHITELISTOFTURNS.getText());
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// WHITELIST OF WORDS // TODO add your handling code here:
		this.wbft.addToWhitelistWord(this.jTextField2WHITELISTOFWORDS.getText());
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		// BLACKLIST OF TURNS // TODO add your handling code here:
		this.wbft.addToWhitelistTurn(this.jTextField3BLACKLISTOFTURNS.getText());
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
		// BLACKLIST END OF TURN // TODO add your handling code here:
		this.wbft.addToBlacklistEndOfTurn(this.jTextField5BLACKLISTENDOFTURN.getText());
	}// GEN-LAST:event_jButton5ActionPerformed

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton6ActionPerformed
		// BLACKLIST PUNCTUATION // TODO add your handling code here:
		this.wbft.addToBlacklistPunctuation(this.jTextField6BLACKLISTPUNCTUATION.getText());
	}// GEN-LAST:event_jButton6ActionPerformed

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton7ActionPerformed
		// PANIC // TODO add your handling code here:
		this.wbft.panicReset();
	}// GEN-LAST:event_jButton7ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(JSimpleWhitelistOfDutchOK.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(JSimpleWhitelistOfDutchOK.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(JSimpleWhitelistOfDutchOK.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(JSimpleWhitelistOfDutchOK.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new JSimpleWhitelistOfDutchOK().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JTextField jTextField1WHITELISTOFTURNS;
	private javax.swing.JTextField jTextField2WHITELISTOFWORDS;
	private javax.swing.JTextField jTextField3BLACKLISTOFTURNS;
	private javax.swing.JTextField jTextField4BLACKLISTOFWORDS;
	private javax.swing.JTextField jTextField5BLACKLISTENDOFTURN;
	private javax.swing.JTextField jTextField6BLACKLISTPUNCTUATION;
	// End of variables declaration//GEN-END:variables
}
